[package]
name = "facet-egui"
version = "0.1.0"
edition = "2024"

[features]
default = ["std", "egui"]
std = ["facet/std", "facet-reflect/std", "thiserror/std"]
egui = ["dep:egui"]

[dependencies]
egui = { version = "0.33.3", default-features = false, optional = true }
facet = { version = "0.43.2", default-features = false, features = ["alloc"] }
facet-reflect = { version = "0.43.2", default-features = false, features = [
    "alloc",
] }

derive_more = { version = "2.1", default-features = false, features = [
    "from",
    "deref",
    "deref_mut",
    "debug",
] }

thiserror = { version = "2", default-features = false }

[dev-dependencies]
eframe = { version = "0.33" }
color-eyre = { version = "0.6" }
