[package]
name = "facet-maybe-mut"
version = "0.1.0"
edition = "2024"
authors = ["Erik Tesar <erik@erik-tesar.com>"]
license = "MIT OR Apache-2.0"
description = "Utility crate to abstract away lock primitives in facet"
readme = "README.md"
repository = "https://github.com/Erik1000/facet-egui"
categories = ["concurrency"]
keywords = ["facet", "reflections", "rwlock", "mutex", "sync"]

[dependencies]
facet = { version = "0.46", default-features = false, features = [
    "alloc",
    "std",
] }
facet-reflect = { version = "0.46", default-features = false, features = [
    "alloc",
    "std",
] }

derive_more = { version = "2.1", default-features = false, features = [
    "from",
    "deref",
    "deref_mut",
    "debug",
] }
thiserror = { version = "2", default-features = false }

[dev-dependencies]
facet-testhelpers = "0.46"
