[package]
name = "facet-egui"
version = "0.0.2"
edition = "2024"
authors = ["Erik Tesar <erik@erik-tesar.com>"]
license = "MIT OR Apache-2.0"
description = "An egui inspector/editor widget for any type that implements Facet"
readme = "../README.md"
repository = "https://github.com/Erik1000/facet-egui"
categories = ["gui", "graphics"]
keywords = ["facet", "reflections", "egui", "probe"]

[[test]]
name = "comparison_egui_probe"
harness = false

[features]
default = ["std"]
std = ["facet/std", "facet-reflect/std", "thiserror/std"]

[dependencies]
facet-maybe-mut.workspace = true

egui = { version = "0.34", default-features = false }
facet = { version = "0.46", default-features = false, features = ["alloc"] }
facet-reflect = { version = "0.46", default-features = false, features = [
    "alloc",
] }

derive_more = { version = "2.1", default-features = false, features = [
    "from",
    "deref",
    "deref_mut",
    "debug",
] }

thiserror = { version = "2", default-features = false }
log = "0.4"

[dev-dependencies]
eframe = { version = "0.34" }
color-eyre = { version = "0.6" }
egui-probe = { version = "0.11.0", features = ["derive"] }
facet-testhelpers = "0.46"


# [patch.crates-io]
# facet = { git = "https://github.com/facet-rs/facet.git" }
# facet-reflect = { git = "https://github.com/facet-rs/facet.git" }
